### ISSUE TITLE
1MD Hub - Form Designs, Meetups, & BUIDL Network

### ISSUE THREAD

**Issue by orbro** [rapid-eth/rapid-adventures#118]
Improve the designs of the popup forms in 1MD site; 
Improve the design of Meetup section of the Events page
Add BUIDL network section to the Events page

**Comment by onpaws** [comment]
- [x] Improve the design of Meetup section of the Events page
- [x] Add BUIDL network section.
- [x] Improve the designs of the popup forms in 1MD site

**Comment by onpaws** [comment]
For the Meetup section, we deployed @Robbiekruszynski 's latest [pr](https://github.com/rapid-eth/1md-map/pull/2)

**Comment by onpaws** [comment]
tabling the popup forms as of yesterday's hand over
