### ISSUE TITLE
RAPID Adventures - Onboarding/Registration Flow Development

### ISSUE THREAD

**Issue by orbro** [rapid-eth/rapid-adventures#120]

**Comment by onpaws** [comment]
- [ ] Implement Homepage container
- [ ] Implement 'default' modal [exam](https://www.figma.com/proto/okKyepLueXXDiJL7uLtEZd/Questing-Platform-Wireframes?node-id=91%3A21&scaling=min-zoom)
- [ ] Implement [signin](https://www.figma.com/proto/okKyepLueXXDiJL7uLtEZd/Questing-Platform-Wireframes?node-id=146%3A90&scaling=min-zoom)
- [ ] Implement [signup](https://www.figma.com/proto/okKyepLueXXDiJL7uLtEZd/Questing-Platform-Wireframes?node-id=231%3A320&scaling=min-zoom)

- [ ] In cases where behavior is driven by Metamask/ethers-react-system/3box profiles, coordinate with @KamesCG to see where edits will make sense.
