### ISSUE TITLE
ETH Denver [ Team Details ] 

### ISSUE THREAD

**Issue by Robbiekruszynski** [rapid-eth/rapid-adventures#125]
ETHDenver 2020 Schedule

Feb 10-13: BUIDL Week, Denver/Boulder/Colorado Springs/Fort Collins
Feb 14-16: ETHDenver 2020 Buidlathon, Sports Castle

14th: Workshops & #BUIDLing
15th: Panels, Workshops & #BUIDLing
16th: Project Fair, Presentations & Closing Ceremony
Feb 16, 5-10pm: ETHDenver After Party, Sports Castle
Feb 17-20: Mountain Retreat, Breckenridge Ski Resort – Limited Discount Rooms Available, Must Book ASAP

** RAPID Dates: 02 / 10 / 20 -- 02/17/20**
These dates cover the week of the hackathon + the day after closing ceremonies
They do not cover the retreat after.
link here: https://www.ethdenver.com/retreat/

**Tickets purchased: ** 
- [x] Billy 
fly in: 02/10/20 
fly out: 02/??/20

- [ ] Kames
fly in: 02/??/20 
fly out: 02/??/20

- [x] Joe
fly in: 02/12/20 
fly out: 02/17/20

- [x] Robbie
fly in: 02/10/20 
fly out: 02/17/20

**Planning on going to the retreat:** 
- [ ] Billy
- [x] Kames
- [ ] Joe
- [ ] Robbie

Air b&b wishlist: 
https://www.airbnb.com/wishlists/706873274

**Comment by Robbiekruszynski** [comment]
Lodging is taken care of
-When you book put it in the ETH travel doc

**Comment by Robbiekruszynski** [comment]
Make a ticket to track events pushing into event 
Kames speaking at DAO(f)

**Comment by joeb000** [comment]
> -When you book put it in the ETH travel doc

Where is this doc?
