### ISSUE TITLE
R.A [ Click Flow ] 

### ISSUE THREAD

**Issue by Robbiekruszynski** [rapid-eth/rapid-adventures#134]
user has the ability to flow from 
- [x] on-boarding 
- [x] metamask check 
- [x] 3box check / form pass 
- [x] dashboard / first adventure 
- [x] quest line 
- [x] quest completion

**Comment by Robbiekruszynski** [comment]
@onpaws even though design is being rework would you agree this flow is complete?

**Comment by onpaws** [comment]
Yes, I think so
