### ISSUE TITLE
R.A. [ETH Denver] Ready

### ISSUE THREAD

**Issue by Robbiekruszynski** [rapid-eth/rapid-adventures#150]
- [x] Epic containing all tickets related to Rapid Adventures show ready for ETH Denver 

- [ ] bundle this EPIC into ETH Denver Package to reduce EPIC ticket noise. 

- [x] Check in with Pat to build this out

- [x] on boarding 
- [x] dashboard 
- [x] adventure guide 
- [x] quest introduction 
- [x] quest completion 
- [x] cert store 
- [x] cert redeem

**Comment by robbiekruszynski** [comment]
closing this EPIC off until it's determined what the future for RA is
