### ISSUE TITLE
Certificate Dapp [ ETH Denver ] Ready 

### ISSUE THREAD

**Issue by Robbiekruszynski** [rapid-eth/rapid-adventures#156]
- [x] version 1 completed and reviewed within RAPID 
- [x] Version 2 completed and reviewed within RAPID 
- [x] Dapp ready for launch

**Comment by Robbiekruszynski** [comment]
@orbro take a look at this

**Comment by orbro** [comment]
Looks great. Just opened a pull request with minor edits @joeb000

**Comment by Robbiekruszynski** [comment]
project complete 
Closing
