### ISSUE TITLE
R.A. [ Header ] v1 build

### ISSUE THREAD

**Issue by Robbiekruszynski** [rapid-eth/rapid-adventures#157]
- [x] Build out header 
- [x] Current Network
- [x] Total Mesh
- [ ] profile name / pic 
______________________________
- [ ] [ discuss ] eth / tipbox needed? 
- [ ] [ discuss ] notification alarm

![topNav2.png](https://images.zenhubusercontent.com/5d917b1dffcf5800019602ba/3078adc7-edda-4f93-9d23-8619775706c9)
______________________________
![topBar.png](https://images.zenhubusercontent.com/5d917b1dffcf5800019602ba/584e3b52-3a8e-4d6c-94df-4a4076fb921b)

**Comment by onpaws** [comment]
I have a the header built out.
Am investigating using 3Box for the profile dropdown.
Found two libraries they publish that seem like potential great fits...
Stay tuned
