### ISSUE TITLE
EthDenver - 1MD Badge & ConsenSys Badge

### ISSUE THREAD

**Issue by orbro** [rapid-eth/rapid-adventures#163]
We need to submit our Badges to the EthDenver folks ASAP.

1MD can probably be one of Tsvetan's designs.

But we need one for the ConsenSys Adventure.

Context here:
https://www.notion.so/BuffiDAO-Sponsor-Integration-Manual-Version-0-0-5-3f3e9cfc4ebf4c0cb424a63cd911097d

**Comment by Robbiekruszynski** [comment]
![OMDbadge](https://user-images.githubusercontent.com/41847310/73706966-dfba3e00-46ae-11ea-9503-fab6e3b19349.png)
![consensysBadge](https://user-images.githubusercontent.com/41847310/73706968-e1840180-46ae-11ea-9ee6-7985ff18efca.png)
![OMDkudos](https://user-images.githubusercontent.com/41847310/73706973-e5b01f00-46ae-11ea-8857-5ff7f0b4512d.png)

**Comment by Robbiekruszynski** [comment]
@orbro is this ticket done?

**Comment by Robbiekruszynski** [comment]
@Robbiekruszynski sending over a package to Austin gathering both the details for the quests with OMD and Consensys along with URL to ETH quests (get from Kames)
