### ISSUE TITLE
[Library] Add Ethers React System

### ISSUE THREAD

**Issue by KamesCG** [rapid-eth/rapid-adventures#31]
The new `ethers-react-system` needs to be added to `rapid-adventures`

1. Add Provider to to Application Root
2. Run any initial tests to ensure it's working i.e. load/init contracts

**Comment by onpaws** [comment]
https://github.com/rapid-eth/rapid-adventures/pulls

**Comment by onpaws** [comment]
https://github.com/rapid-eth/rapid-adventures/pulls

**Comment by onpaws** [comment]
this is completed. closing
