### ISSUE TITLE
[Functional Test] As a user, I can login with Metamask.

### ISSUE THREAD

**Issue by orbro** [rapid-eth/rapid-adventures#89]
**In Scope**
User is able to 'login' with Metamask so they can interact with the appliaction.

**Out of Scope**
Login with 3box
Login with anything besides Metamask
Create a 3box profile
Edit your 3box profile

**Comment by KamesCG** [comment]
Shipped.

https://github.com/rapid-eth/rapid-adventures/blob/dev/packages/ethers-react-system/src/requests/useCommonEnable.js

<img width="1419" alt="Screen Shot 2019-12-08 at 9 20 21 AM" src="https://user-images.githubusercontent.com/3408362/70391547-09e7cc00-199c-11ea-8799-e94f2b75cfc5.png">
